services:
  - type: web
    name: moy-teply-dom
    runtime: static
    staticPublishPath: .
    buildCommand: ""
    routes:
      - type: rewrite
        source: /
        destination: /v2/index.html
